# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 702fd4ab384058853dc0d6aa3ea85e633f8977f10356f90ee270c0c0e03a5f3750985cbac76373f0cd63c104c647ed41f8fd2d5733bc55045d81bacef2958662

test:
  secret_key_base: b7757624f3891b63cd26e3d56ad1037b423e7d11fca41c91d96a6da8dc18115cc555b3ddf22b78ba0c456c758ec523029dbf60113a7e6a6c4e2861a9b9a3dbe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
